services:
  app:
    container_name: yuchi-server
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8888:8888'
    networks:
      - backend
    env_file:
      - .env.prod
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 3.75g

  yuchi-redis:
    image: redis:7.0-alpine
    container_name: yuchi-redis
    networks:
      - backend

  yuchi-redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: yuchi-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=yuchi-redis
    ports:
      - 8082:8081
    networks:
      - backend

  yuchi-postgres:
    image: postgres:16.2
    container_name: yuchi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB_MAIN: ${DB_MAIN}
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  pg_data:
  node_modules:
